# 异常

Java异常类型结构图

![1758854359003](image/基础/1758854359003.png)

## Exception和Error区别

* **`Exception`** :程序本身可以处理的异常，可以通过 `catch` 来进行捕获。`Exception` 又可以分为 Checked Exception (受检查异常，必须处理) 和 Unchecked Exception (不受检查异常，可以不处理)。
* **`Error`** ：`Error` 属于程序无法处理的错误 ，不建议通过 `catch`捕获 。例如 Java 虚拟机运行错误（`Virtual MachineError`）、虚拟机内存不够错误(`OutOfMemoryError`)、类定义错误（`NoClassDefFoundError`）等 。这些异常发生时，Java 虚拟机（JVM）一般会选择线程终止。

## Checked Exception 和 Unchecked Exception 区别

* **`Checked Exception`** 即 受检查异常 ，Java 代码在编译过程中，如果受检查异常没有被 `catch`或者 `throws` 关键字处理的话，就没办法通过编译。
* **`Unchecked Exception`** 即 不受检查异常 ，Java 代码在编译过程中 ，我们即使不处理不受检查异常也可以正常通过编译。
* 除了 `RuntimeException`及其子类以外，其他的 `Exception`类及其子类都属于受检查异常 。

## Throwable 常用方法

* `String getMessage()`: 返回异常发生时的详细信息
* `String toString()`: 返回异常发生时的简要描述
* `String getLocalizedMessage()`: 返回异常对象的本地化信息。使用 `Throwable` 的子类覆盖这个方法，可以生成本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与 `getMessage()`返回的结果相同
* `void printStackTrace()`: 在控制台上打印 `Throwable` 对象封装的异常信息

## try-catch-finally

* `try`块：用于捕获异常。其后可接零个或多个 `catch` 块，如果没有 `catch` 块，则必须跟一个 `finally` 块。
* `catch`块：用于处理 try 捕获到的异常。
* `finally` 块：无论是否捕获或处理异常，`finally` 块里的语句都会被执行。当在 `try` 块或 `catch` 块中遇到 `return` 语句时，`finally` 语句块将在方法返回之前被执行。
* **不要在 finally 语句块中使用 return，因为 try 语句中的 return 返回值会先被暂存在一个本地变量中，当执行到 finally 语句中的 return 之后，这个本地变量的值就变为了 finally 语句中的 return 返回值。
* 在某些情况下，finally 中的代码不会被执行。

  * 程序所在的线程死亡。
  * 关闭 CPU。

## try-with-resources

## 异常使用

* 不要把异常定义为静态变量，因为这样会导致异常栈信息错乱。每次手动抛出异常，我们都需要手动 new 一个异常对象抛出。
* 抛出的异常信息一定要有意义。
* 建议抛出更加具体的异常，比如字符串转换为数字格式错误的时候应该抛出 `NumberFormatException`而不是其父类 `IllegalArgumentException`。
* 避免重复记录日志
* 捕获到异常并再次抛出时，一定要留住原始异常，否则很难定位第一案发现场

## NullPointerException

* 早暴露早修复，严谨使用 `catch` 捕获
* 成员变量定义时初始化
* 返回空字符串、空数组而不是 `null`
* 如果调用方一定要根据 `null`判断，比如返回 `null`表示文件不存在，那么考虑返回 `Optional<T>`
